"use client";

import { useEffect, useState } from "react";
import type { OperationsBrief } from "@/lib/types";

export function Brief() {
  const [brief, setBrief] = useState<OperationsBrief | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    let active = true;
    fetch("/api/brief")
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((d) => {
        if (active) setBrief(d);
      })
      .catch(() => active && setError(true))
      .finally(() => active && setLoading(false));
    return () => {
      active = false;
    };
  }, []);

  if (loading) {
    return (
      <div className="space-y-3">
        <div className="h-5 w-64 animate-pulse rounded bg-surface-2" />
        <div className="h-4 w-full animate-pulse rounded bg-surface-2" />
        <div className="h-4 w-5/6 animate-pulse rounded bg-surface-2" />
        <div className="h-4 w-3/4 animate-pulse rounded bg-surface-2" />
      </div>
    );
  }

  if (error || !brief) {
    return (
      <p className="text-sm text-ink-muted">
        The operations brief is unavailable right now. Metrics remain available
        across the rest of the page.
      </p>
    );
  }

  return (
    <div>
      <div className="flex items-start justify-between gap-4">
        <p className="text-[0.9375rem] leading-relaxed text-ink/90">{brief.body}</p>
      </div>

      <div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 border-t border-line pt-4">
        {brief.references.map((r) => (
          <div key={r.label}>
            <div className="text-[0.625rem] uppercase tracking-eyebrow text-ink-faint">
              {r.label}
            </div>
            <div className="font-mono text-sm tabular-nums text-ink">{r.value}</div>
          </div>
        ))}
      </div>

      <div className="mt-4 text-[0.6875rem] text-ink-faint">
        {brief.generatedBy === "llm"
          ? "Generated by AI from deterministic application metrics."
          : "Generated from deterministic application metrics (AI unavailable)."}
      </div>
    </div>
  );
}
